FROM golang:1.24-alpine

# Install goose to /go/bin
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /app

COPY db/migrations ./db/migrations

# Copy goose binary to a standard path
RUN cp /go/bin/goose /usr/local/bin/goose

ENTRYPOINT ["goose"]