// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Todo struct {
	ID          int32
	Description string
	Completed   bool
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}
